# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/neerajsarna/sciebo/DG_MPI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/neerajsarna/sciebo/DG_MPI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/neerajsarna/sciebo/DG_MPI/CMakeFiles /Users/neerajsarna/sciebo/DG_MPI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/neerajsarna/sciebo/DG_MPI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named 1D_advection_sin.out

# Build rule for target.
1D_advection_sin.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1D_advection_sin.out
.PHONY : 1D_advection_sin.out

# fast build rule for target.
1D_advection_sin.out/fast:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/build
.PHONY : 1D_advection_sin.out/fast

1D_advection_sin.o: 1D_advection_sin.cc.o

.PHONY : 1D_advection_sin.o

# target to build an object file
1D_advection_sin.cc.o:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/1D_advection_sin.cc.o
.PHONY : 1D_advection_sin.cc.o

1D_advection_sin.i: 1D_advection_sin.cc.i

.PHONY : 1D_advection_sin.i

# target to preprocess a source file
1D_advection_sin.cc.i:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/1D_advection_sin.cc.i
.PHONY : 1D_advection_sin.cc.i

1D_advection_sin.s: 1D_advection_sin.cc.s

.PHONY : 1D_advection_sin.s

# target to generate assembly for a file
1D_advection_sin.cc.s:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/1D_advection_sin.cc.s
.PHONY : 1D_advection_sin.cc.s

src/ic_bc_base.o: src/ic_bc_base.cc.o

.PHONY : src/ic_bc_base.o

# target to build an object file
src/ic_bc_base.cc.o:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/src/ic_bc_base.cc.o
.PHONY : src/ic_bc_base.cc.o

src/ic_bc_base.i: src/ic_bc_base.cc.i

.PHONY : src/ic_bc_base.i

# target to preprocess a source file
src/ic_bc_base.cc.i:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/src/ic_bc_base.cc.i
.PHONY : src/ic_bc_base.cc.i

src/ic_bc_base.s: src/ic_bc_base.cc.s

.PHONY : src/ic_bc_base.s

# target to generate assembly for a file
src/ic_bc_base.cc.s:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/src/ic_bc_base.cc.s
.PHONY : src/ic_bc_base.cc.s

src/solve_system.o: src/solve_system.cc.o

.PHONY : src/solve_system.o

# target to build an object file
src/solve_system.cc.o:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/src/solve_system.cc.o
.PHONY : src/solve_system.cc.o

src/solve_system.i: src/solve_system.cc.i

.PHONY : src/solve_system.i

# target to preprocess a source file
src/solve_system.cc.i:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/src/solve_system.cc.i
.PHONY : src/solve_system.cc.i

src/solve_system.s: src/solve_system.cc.s

.PHONY : src/solve_system.s

# target to generate assembly for a file
src/solve_system.cc.s:
	$(MAKE) -f CMakeFiles/1D_advection_sin.out.dir/build.make CMakeFiles/1D_advection_sin.out.dir/src/solve_system.cc.s
.PHONY : src/solve_system.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... debug"
	@echo "... release"
	@echo "... 1D_advection_sin.out"
	@echo "... 1D_advection_sin.o"
	@echo "... 1D_advection_sin.i"
	@echo "... 1D_advection_sin.s"
	@echo "... src/ic_bc_base.o"
	@echo "... src/ic_bc_base.i"
	@echo "... src/ic_bc_base.s"
	@echo "... src/solve_system.o"
	@echo "... src/solve_system.i"
	@echo "... src/solve_system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

