# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ns179556/DG_MPI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ns179556/DG_MPI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ns179556/DG_MPI/CMakeFiles /home/ns179556/DG_MPI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ns179556/DG_MPI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named heat_conduction.out

# Build rule for target.
heat_conduction.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heat_conduction.out
.PHONY : heat_conduction.out

# fast build rule for target.
heat_conduction.out/fast:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/build
.PHONY : heat_conduction.out/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

2x3v_moments_HC.o: 2x3v_moments_HC.cc.o
.PHONY : 2x3v_moments_HC.o

# target to build an object file
2x3v_moments_HC.cc.o:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/2x3v_moments_HC.cc.o
.PHONY : 2x3v_moments_HC.cc.o

2x3v_moments_HC.i: 2x3v_moments_HC.cc.i
.PHONY : 2x3v_moments_HC.i

# target to preprocess a source file
2x3v_moments_HC.cc.i:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/2x3v_moments_HC.cc.i
.PHONY : 2x3v_moments_HC.cc.i

2x3v_moments_HC.s: 2x3v_moments_HC.cc.s
.PHONY : 2x3v_moments_HC.s

# target to generate assembly for a file
2x3v_moments_HC.cc.s:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/2x3v_moments_HC.cc.s
.PHONY : 2x3v_moments_HC.cc.s

src/ic_bc_base.o: src/ic_bc_base.cc.o
.PHONY : src/ic_bc_base.o

# target to build an object file
src/ic_bc_base.cc.o:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/ic_bc_base.cc.o
.PHONY : src/ic_bc_base.cc.o

src/ic_bc_base.i: src/ic_bc_base.cc.i
.PHONY : src/ic_bc_base.i

# target to preprocess a source file
src/ic_bc_base.cc.i:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/ic_bc_base.cc.i
.PHONY : src/ic_bc_base.cc.i

src/ic_bc_base.s: src/ic_bc_base.cc.s
.PHONY : src/ic_bc_base.s

# target to generate assembly for a file
src/ic_bc_base.cc.s:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/ic_bc_base.cc.s
.PHONY : src/ic_bc_base.cc.s

src/solve_system.o: src/solve_system.cc.o
.PHONY : src/solve_system.o

# target to build an object file
src/solve_system.cc.o:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/solve_system.cc.o
.PHONY : src/solve_system.cc.o

src/solve_system.i: src/solve_system.cc.i
.PHONY : src/solve_system.i

# target to preprocess a source file
src/solve_system.cc.i:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/solve_system.cc.i
.PHONY : src/solve_system.cc.i

src/solve_system.s: src/solve_system.cc.s
.PHONY : src/solve_system.s

# target to generate assembly for a file
src/solve_system.cc.s:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/solve_system.cc.s
.PHONY : src/solve_system.cc.s

src/solve_system_SS.o: src/solve_system_SS.cc.o
.PHONY : src/solve_system_SS.o

# target to build an object file
src/solve_system_SS.cc.o:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/solve_system_SS.cc.o
.PHONY : src/solve_system_SS.cc.o

src/solve_system_SS.i: src/solve_system_SS.cc.i
.PHONY : src/solve_system_SS.i

# target to preprocess a source file
src/solve_system_SS.cc.i:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/solve_system_SS.cc.i
.PHONY : src/solve_system_SS.cc.i

src/solve_system_SS.s: src/solve_system_SS.cc.s
.PHONY : src/solve_system_SS.s

# target to generate assembly for a file
src/solve_system_SS.cc.s:
	$(MAKE) -f CMakeFiles/heat_conduction.out.dir/build.make CMakeFiles/heat_conduction.out.dir/src/solve_system_SS.cc.s
.PHONY : src/solve_system_SS.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... debug"
	@echo "... edit_cache"
	@echo "... heat_conduction.out"
	@echo "... rebuild_cache"
	@echo "... release"
	@echo "... 2x3v_moments_HC.o"
	@echo "... 2x3v_moments_HC.i"
	@echo "... 2x3v_moments_HC.s"
	@echo "... src/ic_bc_base.o"
	@echo "... src/ic_bc_base.i"
	@echo "... src/ic_bc_base.s"
	@echo "... src/solve_system.o"
	@echo "... src/solve_system.i"
	@echo "... src/solve_system.s"
	@echo "... src/solve_system_SS.o"
	@echo "... src/solve_system_SS.i"
	@echo "... src/solve_system_SS.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

